# Generated by Django 4.1.2 on 2022-11-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crackSegmentation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload", name="title", field=models.TextField(null=True),
        ),
    ]
